# Generated by Django 3.2.9 on 2021-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(default='blog/images/ezra-jeffrey-comeau-unsplash.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
